### PR TITLE
Add bors config file and adapt Travis settings for bors

### PR DESCRIPTION
**Pull request by ararslan**
Same thing we did for AWSCore. This should allow the stored AWS credentials to be used for pull requests.

### CODE REVIEW

**Comment by ararslan** [comment]
I guess I need to turn off PR builds in the Travis settings.

Also, bors try

**Comment by omus** [comment]
I disabled the "Build pushed pull requests" here: https://travis-ci.org/JuliaCloud/AWSS3.jl/settings

**Comment by omus** [comment]
bors try

**Comment by omus** [comment]
Looks like my invocation worked (https://travis-ci.org/JuliaCloud/AWSS3.jl/builds/492918409)

**Comment by ararslan** [comment]
Hm, okay. So the Mac build stalled and the Linux build legitimately failed a test.

**Comment by omus** [comment]
Do you want to dig into this or do you need some assistance?

**Comment by ararslan** [comment]
I think I'll need some assistance for this one.

**Comment by mattBrzezinski** [comment]
I think we can close this PR?

**Pull request closed without merging**
