### PR TITLE
Set FilePathsBase compatibility to 0.9.11 - 0.9.15

### LINKED ISSUE #227: CI test failure:  MethodError: no method matching parse(::Type{S3Path{Nothing}}, ::S3Path{Nothing})
The following error occurs several times in [current CI pipelines](https://github.com/JuliaCloud/AWSS3.jl/runs/4390051615?check_suite_focus=true):
```
MethodError: no method matching parse(::Type{S3Path{Nothing}}, ::S3Path{Nothing})
  Closest candidates are:
    parse(::Type{P}, ::AbstractString; kwargs...) where P<:AbstractPath at ~/.julia/packages/FilePathsBase/qgXdE/src/path.jl:77
  Stacktrace:
    [1] _broadcast_getindex_evalf
      @ ./broadcast.jl:670 [inlined]
    [2] _broadcast_getindex
      @ ./broadcast.jl:653 [inlined]
    [3] getindex
      @ ./broadcast.jl:597 [inlined]
    [4] copy
      @ ./broadcast.jl:899 [inlined]
    [5] materialize
      @ ./broadcast.jl:860 [inlined]
    [6] readpath(p::S3Path{Nothing}; join::Bool, sort::Bool)
      @ FilePathsBase ~/.julia/packages/FilePathsBase/qgXdE/src/path.jl:713
    [7] readpath
      @ ~/.julia/packages/FilePathsBase/qgXdE/src/path.jl:708 [inlined]
    [8] macro expansion
      @ /opt/hostedtoolcache/julia/1.7.0/x64/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
    [9] macro expansion
      @ ~/work/AWSS3.jl/AWSS3.jl/test/s3path.jl:59 [inlined]
   [10] macro expansion
      @ /opt/hostedtoolcache/julia/1.7.0/x64/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
   [11] test_s3_readpath(p::PathSet{S3Path{Nothing}})
      @ Main ~/work/AWSS3.jl/AWSS3.jl/test/s3path.jl:57
```
Likely causes are changes in FilePathsBase or the S3 bucket failing to be created/being deleted by another pipeline.  I haven't investigated the error fully but the last successful pipeline was 15 days ago. FilePathsBase was at v0.9.15 on the last successful run. It is now at v0.9.17.

### PR DESCRIPTION
**Pull request by omus**
Fixes #227 by avoiding using FilePathsBase versions that require `readdir` when using `join=true` to return strings. As changing the return type could be breaking for some users we'll just limit the versions of FilePathsBase supported here for now for this release. For AWSS3.jl version 0.10 we'll correct that problem in this package and start using a minimum version of FilePathsBase 0.9.16

At first glance appears to address #226 but it does not as we are just temporarily setting an upperbound.

Also, we cannot use Pkg version ranges using a hypen as that requires a minimum version of Julia 1.4

### CODE REVIEW

**Comment by omus** [comment]
bors try

**Comment by omus** [comment]
I've managed to trigger bors today with a `bors r+` but not with `bors try`. I'll do some experimentation here

**Comment by omus** [comment]
bors p=1

**Comment by omus** [comment]
bors try

**Comment by ericphanson** [comment]
if we want to take this approach, we will also need to edit the registry and add this cap to all previous versions of AWSS3 since `readdir( ;join)` was introduced, otherwise the resolver will just give you e.g. AWSS3 v0.9.2 + FilePathsBase v0.9.16

**Comment by omus** [comment]
> if we want to take this approach, we will also need to edit the registry and add this cap to all previous versions of AWSS3 since `readdir( ;join)` was introduced, otherwise the resolver will just give you e.g. AWSS3 v0.9.2 + FilePathsBase v0.9.16

I'm good for doing that as those versions are broken with FilePathsBase 0.9.16

**Comment by omus** [comment]
bors try-

**Comment by omus** [comment]
bors try

**Comment by omus** [comment]
I seem to have set the upper bound to the wrong version

**Comment by omus** [comment]
bors try

**Review by ericphanson — APPROVED** [review]

**Comment by omus** [comment]
I'll merge this in the morning and get a few of the previously stuck PRs merged

**Comment by omus** [comment]
Hmm, looks like there is more investigation to do here. I'll try a re-run to validate the error is reproducible

**Comment by omus** [comment]
bors try

**Comment by omus** [comment]
Interesting. Let's try merging again:

bors r+

**Comment by omus** [comment]
2/3 jobs have finished but the macOS job seems to have failed. I'll wait a little longer but I'll manually merge this if we see another failure. This change is quite simple and the failure are unrelated.

**Pull request merged**
