### PR TITLE
Wait for entries to be available in `isdir` objects channel (0.6 backport)

### PR DESCRIPTION
**Pull request by omus**
Backport of a0a4f48 for AWSS3 version 0.6.

### CODE REVIEW

**Comment by omus** [comment]
bors try

**Comment by mattBrzezinski** [comment]
bors try

**Review by mattBrzezinski — APPROVED** [review]
bors r+

**Comment by mattBrzezinski** [comment]
Trying again.... going to need to start using MockAWS.jl soon this is annoying.

**Comment by mattBrzezinski** [comment]
This PR is failing in random reasons as mentioned in #154 
Going to merge it and tag it as these changes are holding us back.

**Pull request merged**
