### PR TITLE
Use implicit keywords

### PR DESCRIPTION
**Pull request by omus**
Using implicit keywords which were introduced back in Julia 1.5.

### CODE REVIEW

**Comment by omus** [comment]
bors try

**Comment by omus** [comment]
I don't expect bors to work here until #284 is merged but I want to see what will happen here.

**Comment by omus** [comment]
bors try-

**Comment by omus** [comment]
bors try

**Comment by omus** [comment]
bors try-

**Review by mattBrzezinski — APPROVED** [review]

**Pull request merged**
