### PR TITLE
Base.tryparse backport

### PR DESCRIPTION
**Pull request by mattBrzezinski**

### CODE REVIEW

**Comment by rofinn** [comment]
Could probably just tag a patch release of this branch?

**Comment by mattBrzezinski** [comment]
bors try

**Comment by mattBrzezinski** [comment]
Interesting....

**Comment by mattBrzezinski** [comment]
Ran the tests locally, then work as intended and the initial changed passed `bors`.
Let me know if there's anything to change here @rofinn, if not just approved and I'll run the Julia registrator on it.

**Review by rofinn — APPROVED** [review]
LGTM

**Comment by mattBrzezinski** [comment]
Closing as the tag has been created.

https://github.com/JuliaRegistries/General/pull/29673

**Pull request closed without merging**
