### PR TITLE
Format code to be readable and work with JuliaFormatter

### PR DESCRIPTION
**Pull request by omus**
Follow up to https://github.com/JuliaCloud/AWSS3.jl/pull/190 which I found butchered some of the code here. I mostly tried to revise some code where possible to work nicely with the formatter.

In a few cases where I believed the formatter to be wrong I filed issues and disabled it (seems worse to live with code we think is less readable).

Finally, the tests required some additional changes including renaming variables which I think resulted in much nicer tests.

### CODE REVIEW

**Comment by omus** [comment]
bors try

**Review by mattBrzezinski — APPROVED** [review]
LGTM!

**Comment by omus** [comment]
bors try

**Review by mattBrzezinski — APPROVED** [review]

**Pull request merged**
