### PR TITLE
Added proxy kwarg

### PR DESCRIPTION
**Pull request by mattBrzezinski**
## Problem
@octavd is having issues using this package while behind a corporate proxy. We need to pass along a `proxy` through the code pipeline when making the request.

## Solution
When [AWSCore.jl](https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/http.jl#L29) makes the actual request to Amazon we retrieve `http_options` from the request passed in. We can tap into this functionality and add an additional field into our `SymDict` to pass along the proxy value.

## Notes
I believe that this functionality is working correctly, but writing a test for this is overtly complicated. I am able to confirm functionality of this by locally using this branch and doing the following.

```julia
using AWSS3, HTTP

HTTP.request("GET", "https://google.com", proxy=nothing)
> 200 OK

HTTP.request("GET", "https://google.com", proxy="foobar")
> DNSError

s3_get("mattbr-test-bucket", "test.txt"; proxy=nothing)
> 200 OK

s3_get("mattbr-test-bucket", "text.txt"; proxy="foobar")
> DNSERROR
```

### CODE REVIEW

**Comment by mattBrzezinski** [comment]
@octavd if you could clone this repository, pull down this branch and confirm this to be working that would be appreciated!

```bash
git clone https://github.com/JuliaCloud/AWSS3.jl/
cd AWSS3.jl
git fetch
git checkout MB/proxy-kwarg
```

Then
```julia
julia --project
s3_get("bucket", "file"; proxy="corporate")
```

**Comment by octavd** [comment]
Hello @mattBrzezinski,

Thanks for this fix.

I've tested this library as follows:

- s3_list_buckets(aws; proxy="corporate_proxy" ) -> **OK**

- s3_get_file(aws, "your_bucket/specific_folder", "foo.html"; proxy="corporate_proxy") - **NOK**
```
ERROR: ArgumentError: invalid base 10 digit 'e' in "endpoint => \"https:"
Stacktrace:
 [1] parse at ./parse.jl:238 [inlined]
 [2] getconnection(::Type{Sockets.TCPSocket}, ::SubString{String}, ::SubString{String}; keepalive::Bool, connect_timeout::Int64, kw::Base.Iterators.Pairs{Symbol,Any,NTuple{4,Symbol},NamedTuple{(:require_ssl_verification, :iofunction, :verbose, :response_stream),Tuple{Bool,Nothing,Int64,Base.BufferStream}}}) at /opt/app-root/src/.julia/packages/HTTP/IAI92/src/ConnectionPool.jl:625
 [3] #getconnection#29 at /opt/app-root/src/.julia/packages/HTTP/IAI92/src/ConnectionPool.jl:682 [inlined]
 [4] newconnection(::HTTP.ConnectionPool.Pod, ::Type{T} where T, ::SubString{String}, ::SubString{String}, ::Int64, ::Bool, ::Int64; kw::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol,Symbol},NamedTuple{(:iofunction, :verbose, :response_stream),Tuple{Nothing,Int64,Base.BufferStream}}}) at /opt/app-root/src/.julia/packages/HTTP/IAI92/src/ConnectionPool.jl:597
 [5] getconnection(::Type{HTTP.ConnectionPool.Transaction{MbedTLS.SSLContext}}, ::SubString{String}, ::SubString{String}; connection_limit::Int64, pipeline_limit::Int64, idle_timeout::Int64, reuse_limit::Int64, require_ssl_verification::Bool, kw::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol,Symbol},NamedTuple{(:iofunction, :verbose, :response_stream),Tuple{Nothing,Int64,Base.BufferStream}}}) at /opt/app-root/src/.julia/packages/HTTP/IAI92/src/ConnectionPool.jl:541
 [6] request(::Type{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer{Union{}}}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::String; proxy::Nothing, socket_type::Type{T} where T, reuse_limit::Int64, kw::Base.Iterators.Pairs{Symbol,Any,NTuple{4,Symbol},NamedTuple{(:iofunction, :verbose, :require_ssl_verification, :response_stream),Tuple{Nothing,Int64,Bool,Base.BufferStream}}}) at /opt/app-root/src/.julia/packages/HTTP/IAI92/src/ConnectionRequest.jl:73
 [7] request(::Type{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer{Union{}}}}}, ::HTTP.URIs.URI, ::Vararg{Any,N} where N; kw::Base.Iterators.Pairs{Symbol,Any,NTuple{5,Symbol},NamedTuple{(:iofunction, :verbose, :require_ssl_verification, :response_stream, :proxy),Tuple{Nothing,Int64,Bool,Base.BufferStream,Nothing}}}) at /opt/app-root/src/.julia/packages/HTTP/IAI92/src/ExceptionRequest.jl:19
 [8] request(::Type{HTTP.MessageRequest.MessageLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer{Union{}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String; http_version::VersionNumber, target::String, parent::Nothing, iofunction::Nothing, kw::Base.Iterators.Pairs{Symbol,Any,NTuple{4,Symbol},NamedTuple{(:verbose, :require_ssl_verification, :response_stream, :proxy),Tuple{Int64,Bool,Base.BufferStream,Nothing}}}) at /opt/app-root/src/.julia/packages/HTTP/IAI92/src/MessageRequest.jl:51
 [9] request(::Type{HTTP.BasicAuthRequest.BasicAuthLayer{HTTP.MessageRequest.MessageLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer{Union{}}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String; kw::Base.Iterators.Pairs{Symbol,Any,NTuple{4,Symbol},NamedTuple{(:verbose, :require_ssl_verification, :response_stream, :proxy),Tuple{Int64,Bool,Base.BufferStream,Nothing}}}) at /opt/app-root/src/.julia/packages/HTTP/IAI92/src/BasicAuthRequest.jl:28
 [10] macro expansion at /opt/app-root/src/.julia/packages/AWSCore/luFoY/src/http.jl:42 [inlined]
 [11] macro expansion at /opt/app-root/src/.julia/packages/Retry/vS1bg/src/repeat_try.jl:192 [inlined]
 [12] http_request(::Dict{Symbol,Any}) at /opt/app-root/src/.julia/packages/AWSCore/luFoY/src/http.jl:20
 [13] macro expansion at /opt/app-root/src/.julia/packages/AWSCore/luFoY/src/AWSCore.jl:411 [inlined]
 [14] macro expansion at /opt/app-root/src/.julia/packages/Retry/vS1bg/src/repeat_try.jl:192 [inlined]
 [15] do_request(::Dict{Symbol,Any}; return_headers::Bool) at /opt/app-root/src/.julia/packages/AWSCore/luFoY/src/AWSCore.jl:394
 [16] macro expansion at /opt/app-root/src/AWSS3.jl/src/AWSS3.jl:0 [inlined]
 [17] macro expansion at /opt/app-root/src/.julia/packages/Retry/vS1bg/src/repeat_try.jl:192 [inlined]
 [18] s3(::Dict{Symbol,Any}, ::String, ::Dict{Symbol,Any}; headers::Dict{String,String}, path::String, query::Dict{String,String}, version::String, content::String, return_stream::Bool, return_raw::Bool, return_headers::Bool, proxy::Nothing) at /opt/app-root/src/AWSS3.jl/src/AWSS3.jl:88
 [19] #s3_get_file#4 at /opt/app-root/src/AWSS3.jl/src/AWSS3.jl:187 [inlined]
 [20] s3_get_file(::Dict{Symbol,Any}, ::Vararg{Any,N} where N; b::Base.Iterators.Pairs{Symbol,String,Tuple{Symbol},NamedTuple{(:proxy,),Tuple{String}}}) at /opt/app-root/src/AWSS3.jl/src/AWSS3.jl:198
 [21] top-level scope at REPL[20]:1
 [22] run_repl(::REPL.AbstractREPL, ::Any) at /builddir/build/BUILD/julia/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:288
```

- s3_get(aws, "your_bucket/specific_folder", "foo.html"; proxy="corporate_proxy") -> **OK**


- s3_exists(aws, "your_bucket/specific_folder", "foo.html"; proxy="corporate_proxy") -> **OK**

- s3_copy(aws, "your_bucket/specific_folder", "foo.html"; proxy="corporate_proxy") -> **OK**

- s3_delete(aws, "your_bucket/specific_folder", "foo.html"; proxy="corporate_proxy") -> **OK**

- s3_list_objects(aws, "your_bucket/specific_folder"; proxy="corporate_proxy") -> **NOK**

or

- s3_list_objects(aws, "your_bucket", "specific_folder"; proxy="corporate_proxy") -> **NOK**

or

- s3_list_objects(aws, "your_bucket"; proxy="corporate_proxy") -> **NOK**
```
  Channel{Any}(sz_max:0,sz_curr:0)
```
 - s3_list_versions(aws, "your_bucket", "specific_folder"; proxy="corporate_proxy") -> **OK**
 
 - s3_put(aws, "your_bucket", "specific_folder/file", "/opt/app-root/src/data/file"; proxy="corporate_proxy") -> **OK**

**Comment by mattBrzezinski** [comment]
> ERROR: ArgumentError: invalid base 10 digit 'e' in "endpoint => \"https:"

This looks to me like an `HTTP.jl` issue, since the last thing in the log was AWSCore.jl making the [http request](https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/http.jl#L42).

> Channel{Any}(sz_max:0,sz_curr:0)

This might be related to above, I'm not familiar with how channels work. But from what I remember we're just storing all the objects we're getting in this. One thing to ask, are there multiple objects in the bucket which you're making the `ListObjects` request on?

**Comment by octavd** [comment]
Yes, in that buckets there are some folder with subfolders etc.

**Comment by mattBrzezinski** [comment]
> Yes, in that buckets there are some folder with subfolders etc.

I didn't originally write the code here, but it looks like these `ListObject` functions are working as intended. I'm getting the same result back myself. I'll look through the code and try and figure out how to use them and what to expect back.

As for the argument error, I'll have to dive a bit more into it.

**Comment by mattBrzezinski** [comment]
Looked into this some more, the `ArgumentError` for `s3_get_file(aws, "your_bucket/specific_folder", "foo.html")`  is how the function currently works.

**Comment by octavd** [comment]
hmm, and it's ok that it doesn't work?

**Comment by mattBrzezinski** [comment]
> hmm, and it's ok that it doesn't work?

No, it probably should work. But no one has seemed to complain that it's been broken so far. These changes don't affect the current behaviour of it, so I'm okay with putting this forward to unblock you.

Issue for this is logged: https://github.com/JuliaCloud/AWSS3.jl/issues/101

Just waiting for someone to review this, and provide feedback and we can merge it in. I'm also fixing the CI in the mean time as well.

**Comment by octavd** [comment]
Great, looking forward for the new awss3 version. 👍 
Thank you very much, Matt!

**Comment by mattBrzezinski** [comment]
bors try

**Review by iamed2 — APPROVED** [review]

**Comment by mattBrzezinski** [comment]
@octavd new version should be published shortly (~30 minutes) or so.

> https://github.com/JuliaRegistries/General/pull/22606

**Comment by octavd** [comment]
@mattBrzezinski , hmm, I've tried to install now the new version and it grabs 0.7.2 version.
image

and if i try to specify the 0.7.3 version, i am getting the following:

image

Am i doing something wrong?

**Comment by octavd** [comment]
Nevermind, reinstalled IJulia Kernel in the notebook and it worked after.

**Pull request merged**
